### ISSUE TITLE
유저 정보 값 수정

### ISSUE THREAD

**Issue by Yoonyesol** [GU-99/grow-up-fe#128]
## Description

유저 정보 관련하여 수정사항을 반영합니다.

## Todo List

- [ ] 프로필 이미지 변수 변경: `profileImageUrl` -> `profileImageName`
- [ ] 유저 조회 데이터에 `userId`, `provider` 추가
- [ ] mock 데이터 및 타입명 변경

## Estimated Schedule

1시간
