### ISSUE TITLE
수행자 검색 기능 수정

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#147]
## Description
프로젝트원 목록 API가 만들어질 예정이라 이에 맞춰 수행자 검색 기능을 수정하려고 합니다. 기존에 수행자를 검색하면 역할 정보도 같이 내려준다고 생각하여 만들었지만, 가볍게 유저 ID와 닉네임만 내려주는 API로 확정되면서, 추가적으로 역할을 매칭할 필요가 생겼습니다.

## Todo List
- [x] 프로젝트 수행자 검색 API MSW 수정
- [x] 프로젝트원 목록 API 추가
- [x] 수행자 검색 기능 변경

## Estimated Schedule
3시간
