### ISSUE TITLE
수행자 삭제 API를 이용하여 일정 수정 모달에서 수행자 삭제 기능 구현

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#150]
## Description
일정 수정 모달에서 수행자 삭제를 별도의 API로 분리하였으므로, 이를 분리하여 기존에 등록되어 있던 수행자를 삭제하는 기능을 구현합니다.

## Todo List
- [x] 수행자 삭제 API를 위한 React Query 기능 추가
- [x] 수행자 삭제 API를 위한 MSW 처리 추가
- [x] 수행자 삭제 기능 구현

## Estimated Schedule
3시간
