### ISSUE TITLE
유저 검색을 위한 SearchUserInput 컴포넌트 검색 기능 재사용성과 응집력을 위한 수정

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#153]
## Description
일정 수정 모달 작업 중 SearchUserInput 컴포넌트의 검색 기능을 위해 debounce와 abort controller  등의 로직을 다시 작성해야함에 불편을 느껴, 기능의 재사용성과 관련된 기능을 응집하기 위해 한 번 더 리팩토링을 진행하려고 합니다.

## Todo List
- [x] Debounce, Abort Controller  로직 이동
- [x] 키워드 추적과 변경을 상위 컴포넌트에게 위임하기 위해 props 주입 설정
- [x] 유저 선택시 처리 함수는 주입을 통해 유동적인 기능이 가능하도록 설정 

## Estimated Schedule
2시간
