### ISSUE TITLE
팀 수정 모달 UI 및 로직 구현

### ISSUE THREAD

**Issue by ice-bear98** [GU-99/grow-up-fe#165]
## Description
팀 수정 UI를 구현하고 팀 수정 페이지 내 API 및 기능을 구현합니다

## Todo List

- [ ] 팀 수정 UI 구현
- [ ] 팀 수정 페이지 API 구현
- [ ] 팀 수정 페이지 Handler 구현
- [ ] 팀 수정 페이지 type 정

## Estimated Schedule
2일
