### ISSUE TITLE
일정 파일 삭제 API를 이용하여 일정 파일 삭제 구현

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#167]
## Description
일정 수정 모달에서 일정 파일 삭제 API를 이용하여  파일을 삭제하는 기능을 구현합니다.

## Todo List
- [x] 일정 파일 삭제 API를 위한 React Quert 기능 추가
- [x] 일정 파일 삭제 API를 위한 MSW 처리 추가
- [x] 일정 파일 삭제 기능 구현

## Estimated Schedule
3시간
