### ISSUE TITLE
일정 파일 다운로드 API를 이용하여 파일 다운로드 기능 구현

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#168]
## Description
일정 상세 모달에서 일정 파일 다운로드 API를 이용하여 파일 다운로드 기능을 구현합니다.

## Todo List
- [x] 일정 파일 다운로드 API axios 기능 구현
- [x] 일정 파일 다운로드 API MSW 기능 추가
- [x] 파일 다운로드 기능 구현

## Estimated Schedule
3시간
