### ISSUE TITLE
상태 삭제 API를 이용하여 프로젝트 상태 삭제 기능 구현

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#169]
## Description
상태 수정 모달에서 상태 삭제 API를 이용하여 상태 삭제 기능을 구현합니다.

## Todo List
- [ ] 상태 삭제 API를 위한  React Query 기능 추가
- [ ] 상태 삭제 API를 위한 MSW 기능 추가
- [ ] 상태 삭제 기능 구현

## Estimated Schedule
3시간
