### ISSUE TITLE
일정 삭제 API를 이용하여 일정 삭제 기능 구현

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#170]
## Description
일정 상세 모달에서 일정 삭제 API를 이용하여 일정을 삭제하는 기능을 구현합니다.

## Todo List
- [x] 일정 삭제 API를 위한 React Query 기능 추가
- [x] 일정 삭제 API를 위한 MSW 기능 추가
- [x] 일정 삭제 기능 구현

## Estimated Schedule
3시간
