### ISSUE TITLE
일정 수정 모달 파일 업로드 기능 추가

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#187]
## Description
일정 등록 모달에 파일 업로드 기능을 구현했습니다. 이를 이용하여 일정 수정 모달의 파일 업로드 기능을 추가하려고 합니다.

## Todo List
- [x] FileDropZone 컴포넌트 리팩토링
- [x] 일정 파일 관련 useTaskFile 커스텀훅 추가
- [x] 일정 수정 모달 파일 업로드 기능 구현

## Estimated Schedule
1시간
