### ISSUE TITLE
일정 상세 모달의 수정 버튼 클릭시 일정 수정 모달로 변경하는 기능 구현

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#188]
## Description
현재는 일정 상세 모달과 일정 수정 모달을 각각 열어서 필요에 따라 기능 확인을 진행했습니다. 하지만 본래 일정을 클릭하면 상세모달이 보이고, 상세 모달의 수정 버튼을 눌렀을 때 수정 모달로 변경되어야 합니다. 이를 구현하려고 합니다.

## Todo List
- [x] 일정 상세 모달에서 수정 모달 전환을 위한 props 추가 (openUpdateModal) 
- [x] 칸반보드: 일정 상세 모달의 수정 버튼을 통해 수정 모달로 전환
- [x] 캘린더: 일정 상세 모달의 수정 버튼을 통해 수정 모달로 전환

## Estimated Schedule
2시간
