### ISSUE TITLE
프로젝트 생성 기능 구현

### ISSUE THREAD

**Issue by ice-bear98** [GU-99/grow-up-fe#200]
## Description

프로젝트 생성 기능을 구현합니다.

## Todo List

- [ ] 프로젝트 생성 API 및 쿼리 구현
- [ ] 프로젝트 생성 MSW Handler 구현
- [ ] 프로젝트 기능 구현'
## Estimated Schedule

1일
