### ISSUE TITLE
유저 인증을 위한 MSW 수정 및 페이지 라우트 인증 처리

### ISSUE THREAD

**Issue by Yoonyesol** [GU-99/grow-up-fe#228]
## Description

유저 인증을 통한 프로그램 사용이 가능하도록 MSW와 라우트 인증 처리를 추가합니다.

## Todo List

- [x] AfterLoginRoute(접근하기 위해 로그인이 필요한 페이지 라우트)에 유저 인증 추가
- [x] BeforeLoginRoute(로그인이 필요없는 페이지 라우트)에 유저 인증 점검 코드 추가
- [x] 관련 MSW에서 JWT 더미 데이터를 사용하는 코드 삭제

## Estimated Schedule

2시간
