### ISSUE TITLE
상태 추가 모달 UI 작성

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#24]
## Description
특정 프로젝트 관리 페이지에 할일의 상태를 추가하는 모달UI를 작성합니다.

## Todo List
- [x] 색상 선택 라이브러리 탐색
- [x] React Portal 조사
- [x] 모달 공용 레이아웃 작성
- [x] 상태 추가 UI 작성

## Estimated Schedule
3~4시간

**Comment by Seok93** [comment]
### 🎨 색상 선택 라이브러리 후보군
[react-color](https://github.com/casesandberg/react-color?tab=readme-ov-file) vs  [react-colorful](https://github.com/omgovich/react-colorful?tab=readme-ov-file#getting-started) vs [react-color-palette](https://github.com/Wondermarin/react-color-palette)

### 📊 npm trends 다운로드 비교
![color vs colorful vs color-palette png](https://github.com/GU-99/grow-up-fe/assets/32609010/eb4e0d9b-0c67-4eb1-ac62-3c874f67ef32)

### 🎁bundle size 비교
|[react-color](https://bundlephobia.com/package/react-color@2.19.3)|[react-colorful](https://bundlephobia.com/package/react-colorful@5.6.1)|[react-color-palette](https://bundlephobia.com/package/react-color-palette@7.1.1)|
|:---|:---|:---|
|![react-color bundle](https://github.com/GU-99/grow-up-fe/assets/32609010/77bff6ce-b639-4bd3-b269-e88d59248c46)|![react-colorful bundle](https://github.com/GU-99/grow-up-fe/assets/32609010/63383eba-ec04-4f01-ac5d-f2dba2d73041)|![react-color-palette bundle](https://github.com/GU-99/grow-up-fe/assets/32609010/d8bfd6ab-1bff-4a57-a213-9648cc9bbe42)|

### 🤔최종 비교
색상 선택 라이브러리를 검색하면 `react-color`와 `reacr-colorful`에 관련된 내용이 제일 많이 나오고 있고, npm trends를 봐도 많이 사용하고 있음을 알 수 있습니다.  여러 사람들이 사용하는 만큼 어느 정도 안정성이 검증된 라이브러리라고 생각합니다.

`react-color`는 13개의 다양한 색상 선택기(Picker)를 가지고 있어 원하는 상황에 원하는 UI로 예쁘 디자인할 수 있는 장점이 있습니다. DT로 설정되어 있는 것으로 미루어보아 자체적으로 TS를 지원하고 있지는 않지만, 커뮤니티에서 자체적으로 TS를 제공하고 있습니다. 단점으로는 라이브러리의 번들링 사이즈가 크고,  2020년 5월 4일을 기준으로 업데이트가 진행되지 않았습니다. 

`react-colorful`은 트리쉐이킹이 가능하면 작은 번들링 사이즈 (약 13배) 를 가지고 있어 가벼우며 자체적으로 TS를 지원하고 있습니다. 모바일 친화성과 크로스 브라우징 대책도 잘되어 있다고 합니다. 그리고 상대적으로 `react-color`보다 러닝커브도 낮은 편이라 생각합니다. 단점으로는 2022년 9월 10일 이후로 업데이트가 진행되지 않고 있다는 점입니다.

`react-color`와 `react-colorful` 중 이번 프로젝트에 적합하다고 생각하는 라이브러리는 `react-colorful` 입니다. 그 이유는 이번 프로젝트에서 다양한 색상 선택기가 필요하지 않을 뿐더러 비중도 크지 않아 가벼운 패키징 사이즈가 유리하고, 빠른 적용을 위해 러닝 커브가 낮은 점이라고 생각합니다.

`react-color-palette` 는 가장 가볍고 사용법도 간단합니다.  또한 마지막 업데이트가 2024년 4월 10일로 활발하게 업데이트를 진행하고 있습니다. 

`react-colorful`을 선택한 이유가 가볍고, 러닝커브가 낮은 점이라고 했기 때문에 `react-color-palette` 와 유사한 특징을 가지고 있으나, 다운로드 수로 미루어보아 더 검증된 `react-colorful`을 사용하는 것이 좋을 것이라 생각합니다.
