### ISSUE TITLE
프로젝트 수정 기능 API 추가

### ISSUE THREAD

**Issue by ice-bear98** [GU-99/grow-up-fe#246]
## Description
현재 UI만 작업되어 있어서 순차적으로 기능을 연결하려고 합니다. 첫 시작으로 프로젝트 수정 API를 통해 프로젝트 정보가 수정될 수 있도록 기능을 붙이려고 합니다

## Todo List

- [ ] 프로젝트 수정 API Axios 추가
- [ ] 프로젝트 수정 Query 작성
- [ ] 프로젝트 수정 Handler 작성

## Estimated Schedule

5시간
