### ISSUE TITLE
테스트를 위한 환경 설정 추가

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#254]
## Description
실서버와 연결하여 테스트를 진행하기에 앞서 develop, staging, production 환경 설정을 구체적으로 분리하려고 합니다.

## Todo List
- [x] tsconfig production 환경 설정 추가
- [x] staging 환경 테스트를 위한 serve 라이브러리 추가
- [x] build 작업 중 ts 컴파일러에게  잡히는 부분 수정

## Estimated Schedule
1시간
