### ISSUE TITLE
대기 상태에서의 액세스 토큰 만료 처리

### ISSUE THREAD

**Issue by Yoonyesol** [GU-99/grow-up-fe#266]
## Description

~~액세스 토큰 만료 시간 체크 방식을 변경하여, 새로고침 시 인증시간이 만료되거나 대기 상태에서 액세스 토큰이 만료되어 발생하는 문제를 해결합니다.~~ 
대기 상태에서 액세스 토큰이 만료되어 발생하는 문제를 해결합니다.

## Todo List

- [x] ~~액세스 토큰 만료 시간 체크 방식 변경~~
- [x] ~~새로고침 시 인증 시간이 초기화되는 문제 수정~~
- [x] 대기상태에서 액세스 토큰이 만료될 시, 액세스 토큰을 자동으로 재발급 받도록 수정

## Estimated Schedule

1일
