### ISSUE TITLE
검색 기능 사용시 본인 검색 되는 오류 수정

### ISSUE THREAD

**Issue by ice-bear98** [GU-99/grow-up-fe#282]
## Description
검색기능 사용시 본인 검색이 되는 오류가 있어서 MSW 수정

## Todo List

- [ ] 전체 유저 검색시 본인 검색 안되게 수정
- [ ] 팀 유저 검색시 본인 검색 안되게 수정
- [ ] 프로젝트 유저 검색시 본인 검색 안되게 수정

## Estimated Schedule

1일
