### ISSUE TITLE
프로젝트 환경 설정

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#3]
## Description
팀 프로젝트 작업 진행 전 환경 설정

## Todo List
- [x] vite + react + typescript + swc + yarn 기본 환경 세팅
- [x] 라이브러리 추가
- [x] ESLint, Prettier 설정 추가
- [x] Github Template 파일 추가
- [x] husky: pre-commit 단계에서 eslint, prettier 확인하도록 설정 추가

## Estimated Time
2~3일
