### ISSUE TITLE
특정 프로젝트 관리페이지 칸반보드 UI 작성

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#33]
## Description
특정 프로젝트 관리 페이지의 칸반 보드 UI를 작성합니다.

## Todo List
- [x] Kanban UI 작성
- [x] Kanban Todo 드래그 앤 드롭 구현
- [x] Kanban Status 드래그 앤 드롭 구현

## Estimated Schedule
2일
