### ISSUE TITLE
모든 프로젝트 관리 페이지 UI 작성 및 기능구현

### ISSUE THREAD

**Issue by kimpearl3599** [GU-99/grow-up-fe#45]
## Description

유저가 팀의 HEAD가 되어 팀을 생성하거나
유저가 가입된 팀 리스트 및 팀의 모든 프로젝트를 조회할 수 있는 페이지 🔧

## Todo List

- [ ] 팀 목록 Sidebar UI 구현
- [ ] 프로젝트 목록 UI 구현
- [ ] 팀 추가 및 팀 설정 팝업 구현
- [ ] 프로젝트 추가 및 프로젝트 설정 팝업 구현
- [ ] 프로젝트 삭제 구현

## Estimated Schedule

Daily 2-3 hour 작업 😆
