### ISSUE TITLE
특정 프로젝트 관리 페이지 캘린더 UI 작성

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#51]
## Description
특정 프로젝트 관리 페이지의 캘린더 UI를 작성합니다.

## Todo List
- [x] Calendar UI 작성
- [x] Calendar 커스텀 컴포넌트 추가
- [x] 프로젝트 설정 기간 이외의 날짜 처리하기

## Estimated Schedule
3~4일
