### ISSUE TITLE
회원가입 폼 UI 수정 및 관련 로직 수정

### ISSUE THREAD

**Issue by Yoonyesol** [GU-99/grow-up-fe#65]
## Description
바뀐 회원가입 로직에 맞게 회원가입 폼 UI를 수정합니다.

## Todo List
- [x] 입력필드 추가/삭제/수정
- [x] 이미지 필드 데이터 타입 수정
- [x] 인증번호 전송 초시계 구현
- [x] links 필드의 각 링크에 key값 부여
- [x] 전송 버튼 및 로직 일부 수정

## Estimated Schedule
2~3일
