### ISSUE TITLE
유용한 VSCode 확장앱 추가

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#76]
## Description
유용한 VSCode 확장앱을 추천 항목에 추가

## Todo List
- [x] Vitest : 테스트 코드 부분적 실행 및 결과를 확인하는데 도움을 주는 확장앱
- [x] JSDoc Generator: JSDoc을 자동으로 작성해주는 확장앱 (template 작성에 유용)
- [x] JSDoc Markdown highlightiing : JSDoc 가독성을 위한 하이라이팅/스타일 확장앱
- [x] Svg Preview : SVG 이미지를 보여주는 확장앱

## Estimated Schedule
10분
