### ISSUE TITLE
할 일 상세보기 모달 UI 작성 & 기능 개발

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#89]
## Description
특정 프로젝트 페이지 할일 상세보기 모달 UI를 작성합니다.

## Todo List
- [ ] 할 일 상세보기 모달 UI 작성
- [ ] 파일 다운로드 기능 추가
- [ ] 수정 버튼 클릭시 모달 전환 방식 고민하기

## Estimated Schedule
2일
