### ISSUE TITLE
프로젝트 상태, 프로젝트, 할일에 대한 타입 정의 정리

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#94]
## Description
ERD 내용이 확정되었고, API 기능 전반적으로 확정되었으니 프로젝트 상태, 프로젝트, 할일에 대한 타입 정의를 한 번 정리하려고 합니다.

## Todo List
- [x] ProjectStatus 타입 정리
- [x] Project 타입 정리
- [x] Task 타입 정리

## Estimated Schedule
3~4시간
